#### Hacklab Solutions Private Limited

##### Artificial Intelligence (AI/ML) internship

1. The process of estimating the parameters of a camera is called camera calibration.
This means we have all the information (parameters or coefficients) about the camera required to determine an accurate relationship between a 3D point in the real world and its corresponding 2D projection (pixel) in the image captured by that calibrated camera.

Write a python script to automatically find the camera calibration parameters using a 6x8 checkerboard pattern. 
Record a video (or share photographs) to show how the calibration setup works.

You can find the checkerboard pattern here: 

https://raw.githubusercontent.com/MarkHedleyJones/markhedleyjones.github.io/master/media/calibration-checkerboard-collection/Checkerboard-A4-30mm-8x6.pdf


In [1]:
import numpy as np
import cv2 as cv
import glob

In [2]:
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*8,3), np.float32)
objp[:,:2] = np.mgrid[0:8,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.



In [3]:
# Capture images of the checkerboard pattern
images = glob.glob('*.jpg')
for image in images:
    img = cv.imread(image)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (8,6), None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        cv.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)

        # Draw and display the corners
        cv.drawChessboardCorners(img, (8,6), corners, ret)
        cv.imshow("img", img)
        cv.waitKey(0)

cv.destroyAllWindows()

In [4]:
# Calibrate the camera
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)



In [5]:
# Save the camera calibration parameters to a file
np.savez("calibration.npz", mtx=mtx, dist=dist, rvecs=rvecs, tvecs=tvecs)

In [6]:
from numpy import load

data = load('calibration.npz')
lst = data.files
for item in lst:
    print(item)
    print(data[item])

mtx
[[5.51825999e+03 0.00000000e+00 9.49860299e+02]
 [0.00000000e+00 5.52161483e+03 6.78624462e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist
[[-2.98349739e-01  3.59454239e+01  1.94949406e-03 -3.29606696e-03
  -1.14671647e+03]]
rvecs
[[[ 1.44385561e-01]
  [-1.24364322e-02]
  [-6.61647203e-03]]

 [[ 6.37663367e-03]
  [ 7.77621691e-03]
  [ 7.31447933e-05]]]
tvecs
[[[-16.63655932]
  [-11.85275565]
  [116.46980135]]

 [[ -3.91358363]
  [ -2.83149381]
  [ 31.14137059]]]
